[toolchain]
anchor_version = "0.32.1"
[features]
resolution = true
[programs.localnet]
reelmint = "Fg6PaFpoGXkYsidMpWxTWqkZq6W2BeZ7FEfcYkgMQHGz"
[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
