"use client";
import {TransactionConfirmation} from '@/components/transaction-confirmation';
import {confirmationDestination,type ConfirmationResult} from '@/lib/confirmation-poll';
import {ImageUpload,LaunchOptions} from '@/components/launch-options';
import {useEffect,useState} from 'react';
import {LockKeyhole,Wallet,Rocket,ExternalLink,LoaderCircle,ShieldCheck,Coins} from 'lucide-react';
import {walletProvider,connectAddress,messageSignature,assertWalletAccount,walletError,type WalletProvider} from '@/lib/browser-wallet';
import {formProblem} from '@/lib/launch-validation';
async function api(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json() as any;if(!r.ok)throw new Error(d.error||'Request failed.');return d;}
export default function Admin(){
 const [state,setState]=useState<any>(null),[provider,setProvider]=useState<WalletProvider|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[pending,setPending]=useState<{intentId:string;signature:string}|null>(null);
 const [uploading,setUploading]=useState(false);
 const [form,setForm]=useState({description:'The main token of Instara.',image:'',website:'',twitter:'https://x.com/instaraxyz',telegram:'',devBuySol:''});
 async function refresh(){try{const d=await api('admin/state');setState(d);setPending(d.pending||null);}catch(e){setState(null);throw e;}}
 useEffect(()=>{void refresh().catch(()=>{});},[]);
 async function connect(type:'phantom'|'solflare'){
  const p=walletProvider(type,window);if(!p)return setNotice(`Open this page in ${type==='phantom'?'Phantom':'Solflare'} or install its extension.`);
  setBusy(true);setNotice('Approve the connection and verification message in your wallet…');try{const address=await connectAddress(p),c=await api('wallet/challenge',{wallet:address}),signature=await messageSignature(p,c.message);assertWalletAccount(p,address);await api('wallet/verify',{id:c.id,signature});await refresh();setProvider(p);setNotice('Wallet connected.');}catch(e){setState(null);setNotice(walletError(e));}finally{setBusy(false);}
 }
 function confirmed(result:ConfirmationResult){setPending(null);if(!result.ok){setNotice(result.message||'Claim was not completed.');void refresh().catch(e=>setNotice(walletError(e)));return;}const destination=confirmationDestination(result);if(destination){window.location.assign(destination);return;}void refresh().catch(e=>setNotice(walletError(e)));setNotice(result.kind==='main_lookup'?'Claim setup saved.':result.kind==='main_config'?'Launch configuration created and saved.':'Dev-wallet fee claim confirmed.');}
 async function transact(kind:'launch'|'claim'|'config'|'lookup'){
  if(kind==='launch'){const problem=formProblem({...form,name:'Instara',symbol:'INSTARA'},true);if(problem)return setNotice(problem);if(!state?.meteoraConfig)return setNotice('Create the launch configuration first.');if(!state?.enabled)return setNotice('Enable MAIN_LAUNCH_ENABLED in your server environment to launch INSTARA.');}
  if(!provider)return setNotice('Reconnect your authorized wallet to sign the transaction.');setBusy(true);setNotice('Preparing the transaction…');
  try{assertWalletAccount(provider,state.wallet);const prepared=await api(kind==='lookup'?'admin/lookup/prepare':kind==='config'?'admin/config/prepare':kind==='launch'?'admin/prepare':'admin/claim',kind==='launch'?form:{}),{VersionedTransaction}=await import('@solana/web3.js');assertWalletAccount(provider,state.wallet);setNotice('Approve the transaction in your wallet…');const signed=await provider.signTransaction(VersionedTransaction.deserialize(Uint8Array.from(atob(prepared.transaction),c=>c.charCodeAt(0))));const sent=await api('launch/submit',{intentId:prepared.intentId,transaction:btoa(String.fromCharCode(...signed.serialize()))});const value={intentId:prepared.intentId,signature:sent.signature};setPending(value);await refresh();setNotice('Transaction submitted. Confirming automatically…');}catch(e){setNotice(walletError(e));await refresh().catch(()=>{});}finally{setBusy(false);}
 }
 async function recover(configuration=false){setBusy(true);try{await api(configuration?(state.pendingConfig?.kind==='main_lookup'?'admin/lookup/recover':'admin/config/recover'):'launch/recover',configuration?{}:{id:state.token.id});await refresh();setNotice('Expired launch cleared. You can prepare it again.');}catch(e){setNotice(walletError(e));}finally{setBusy(false);}}
 return <div className="app-shell"><header><a className="brand" href="/"><img src="/brand-logo.png" alt="" width="40" height="40"/>insta<span>ra</span></a><span className="locked-badge"><LockKeyhole size={14}/> Private launcher</span><a href="/">Back to launchpad</a></header><main className="admin-main">
 <div className="page-heading"><div className="eyebrow"><ShieldCheck size={14}/> INSTARA MAIN TOKEN</div><h1>One token.<br/><span>At the heart of Instara.</span></h1><p>A private launch space for the platform token.</p></div>
 {notice&&<div role="status" className="notice"><span>{notice}</span></div>}
 {!state?<section className="panel admin-lock"><LockKeyhole size={34}/><h2>Dev wallet access only</h2><p>Connect the authorized dev wallet and sign a message to unlock this page. Signing in does not transfer funds.</p><div className="form-actions"><button className="primary-button" onClick={()=>connect('phantom')} disabled={busy}><Wallet size={16}/> Connect Phantom</button><button className="secondary-button" onClick={()=>connect('solflare')} disabled={busy}>Connect Solflare</button></div></section>:<div className="launch-grid"><section className="panel"><div className="panel-heading"><h2>Launch INSTARA</h2><span className="locked-badge"><ShieldCheck size={14}/> Authorized</span></div>{!state.meteoraConfig&&<div className="fee-note"><div><strong>Create your launch configuration</strong><p>2% trading fee. Starts at 20 SOL market cap and graduates at 250 SOL. Your wallet approves the account creation cost; the address is saved automatically.</p><button className="primary-button" disabled={busy||!!state.pendingConfig} onClick={()=>transact('config')}>Create launch configuration</button>{state.pendingConfig&&<button className="secondary-button" disabled={busy} onClick={()=>recover(true)}>Recover expired setup</button>}</div></div>}<form noValidate onSubmit={e=>{e.preventDefault();void transact('launch');}}>
 <div className="two-fields"><label>Coin name<input value="Instara" readOnly/></label><label>Ticker<input value="INSTARA" readOnly/></label></div>
 <label className="form-label">Description<textarea rows={3} maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><ImageUpload value={form.image} onChange={image=>setForm(f=>({...f,image}))} connected={!!state} disabled={busy||state.token?.status==='launched'} onBusy={setUploading}/><LaunchOptions value={form} onChange={(key,value)=>setForm(f=>({...f,[key]:value}))} disabled={busy||state.token?.status==='launched'}/>
 <div className="fee-note"><Coins size={20}/><div><strong>All creator fees go to the dev wallet.</strong><p>2% trading fee. Meteora takes its protocol share; the remaining creator fees belong to your wallet. No Instagram verification or buyback deduction applies to the main token.</p></div></div>
 {state.token?.status==='launched'?<div className="notice"><span>Main token launched.</span></div>:<button className="primary-button" type="submit" disabled={busy||uploading||!!pending||state.token?.status==='pending'||!!state.configuredMint}><Rocket size={16}/>{pending?'Confirming…':busy?'Preparing…':'Launch main token'}</button>}
 {state.token?.status==='pending'&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>recover()}>Recover expired launch</button>}
 {notice&&<p className="action-feedback" role="status">{notice}</p>}
 </form></section><aside><section className="panel admin-details">{state.meteoraConfig&&<><h3>Launch configuration</h3><code>{state.meteoraConfig}</code><p>Saved automatically. No environment key needed.</p></>}<h3>Dev fee recipient</h3><code>{state.wallet}</code><p>This signed wallet is the Meteora creator and fee recipient.</p>{!provider&&<div className="form-actions"><button className="secondary-button" disabled={busy} onClick={()=>connect('phantom')}>Reconnect Phantom</button><button className="secondary-button" disabled={busy} onClick={()=>connect('solflare')}>Reconnect Solflare</button></div>}
 {pending&&<TransactionConfirmation pending={pending} onConfirmed={confirmed}/>}
 {state.token?.status==='launched'&&<><h3>INSTARA mint</h3><code>{state.token.mint}</code><a href={`https://solscan.io/token/${state.token.mint}`} target="_blank" rel="noreferrer">View on Solscan <ExternalLink size={14}/></a><p>This mint is saved automatically for community buybacks.</p><button className="primary-button" disabled={busy||!!pending} onClick={()=>transact('claim')}><Coins size={16}/> Claim dev fees</button></>}
 {state.configuredMint&&!state.lookupTables&&<><h3>Set up creator claims</h3><p>Create the shared transaction lookup table. Its address is saved automatically.</p><button className="secondary-button" disabled={busy||!!state.pendingConfig} onClick={()=>transact('lookup')}>Prepare creator claims</button>{state.pendingConfig?.kind==='main_lookup'&&<button className="secondary-button" disabled={busy} onClick={()=>recover(true)}>Recover expired setup</button>}</>}<p>Only one main token can be launched through this page.</p>{busy&&<LoaderCircle className="spin" size={18}/>}</section></aside></div>}
 </main></div>;
}
