"use client";
import {useEffect,useState} from 'react';
import {LockKeyhole,Wallet,Rocket,ExternalLink,LoaderCircle,ShieldCheck,Coins} from 'lucide-react';
type WalletProvider={connect():Promise<{publicKey:{toString():string}}>;signMessage(message:Uint8Array,encoding?:string):Promise<{signature:Uint8Array}>;signTransaction(transaction:any):Promise<any>};
async function api(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json() as any;if(!r.ok)throw new Error(d.error||'Request failed.');return d;}
export default function Admin(){
 const [state,setState]=useState<any>(null),[provider,setProvider]=useState<WalletProvider|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[pending,setPending]=useState<{intentId:string;signature:string}|null>(null);
 const [form,setForm]=useState({description:'The main token of Instara.',image:'',metadataUri:''});
 async function refresh(){try{const d=await api('admin/state');setState(d);setPending(d.pending||null);}catch(e){setState(null);throw e;}}
 useEffect(()=>{void refresh().catch(()=>{});},[]);
 async function connect(type:'phantom'|'solflare'){
  const p=type==='phantom'?window.phantom?.solana:window.solflare;if(!p)return setNotice(`Open this page in ${type==='phantom'?'Phantom':'Solflare'} or install its extension.`);
  setBusy(true);setNotice('');try{const connected=await p.connect(),c=await api('wallet/challenge',{wallet:connected.publicKey.toString()}),signature=await p.signMessage(new TextEncoder().encode(c.message),'utf8');await api('wallet/verify',{id:c.id,signature:Array.from(signature.signature)});await refresh();setProvider(p);}catch(e){setState(null);setNotice((e as Error).message);}finally{setBusy(false);}
 }
 async function confirm(value=pending){if(!value)return;setBusy(true);try{const result=await api('launch/confirm',value);await refresh();setNotice(result.kind==='main_lookup'?'Claim setup saved.':result.kind==='main_config'?'Launch configuration created and saved.':result.kind==='main_launch'?'INSTARA is launched. Its mint has been saved automatically.':'Dev-wallet fee claim confirmed.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function transact(kind:'launch'|'claim'|'config'|'lookup'){
  if(!provider)return setNotice('Reconnect your authorized wallet to sign the transaction.');setBusy(true);setNotice('');
  try{const prepared=await api(kind==='lookup'?'admin/lookup/prepare':kind==='config'?'admin/config/prepare':kind==='launch'?'admin/prepare':'admin/claim',kind==='launch'?form:{}),{VersionedTransaction}=await import('@solana/web3.js');const signed=await provider.signTransaction(VersionedTransaction.deserialize(Uint8Array.from(atob(prepared.transaction),c=>c.charCodeAt(0))));const sent=await api('launch/submit',{intentId:prepared.intentId,transaction:btoa(String.fromCharCode(...signed.serialize()))});const value={intentId:prepared.intentId,signature:sent.signature};setPending(value);await confirm(value);}catch(e){setNotice((e as Error).message);await refresh().catch(()=>{});}finally{setBusy(false);}
 }
 async function recover(configuration=false){setBusy(true);try{await api(configuration?(state.pendingConfig?.kind==='main_lookup'?'admin/lookup/recover':'admin/config/recover'):'launch/recover',configuration?{}:{id:state.token.id});await refresh();setNotice('Expired launch cleared. You can prepare it again.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 return <div className="app-shell"><header><a className="brand" href="/"><img src="/brand-logo.png" alt="" width="40" height="40"/>insta<span>ra</span></a><span className="locked-badge"><LockKeyhole size={14}/> Private launcher</span><a href="/">Back to launchpad</a></header><main className="admin-main">
 <div className="page-heading"><div className="eyebrow"><ShieldCheck size={14}/> INSTARA MAIN TOKEN</div><h1>One token.<br/><span>At the heart of Instara.</span></h1><p>A private launch space for the platform token.</p></div>
 {notice&&<div role="status" className="notice"><span>{notice}</span></div>}
 {!state?<section className="panel admin-lock"><LockKeyhole size={34}/><h2>Dev wallet access only</h2><p>Connect the authorized dev wallet and sign a message to unlock this page. Signing in does not transfer funds.</p><div className="form-actions"><button className="primary-button" onClick={()=>connect('phantom')} disabled={busy}><Wallet size={16}/> Connect Phantom</button><button className="secondary-button" onClick={()=>connect('solflare')} disabled={busy}>Connect Solflare</button></div></section>:<div className="launch-grid"><section className="panel"><div className="panel-heading"><h2>Launch INSTARA</h2><span className="locked-badge"><ShieldCheck size={14}/> Authorized</span></div>{!state.meteoraConfig&&<div className="fee-note"><div><strong>Create your launch configuration</strong><p>2% trading fee. Starts at 20 SOL market cap and graduates at 250 SOL. Your wallet approves the account creation cost; the address is saved automatically.</p><button className="primary-button" disabled={busy||!!state.pendingConfig} onClick={()=>transact('config')}>Create launch configuration</button>{state.pendingConfig&&!pending&&<button className="secondary-button" disabled={busy} onClick={()=>recover(true)}>Recover expired setup</button>}</div></div>}<form onSubmit={e=>{e.preventDefault();void transact('launch');}}>
 <div className="two-fields"><label>Coin name<input value="Instara" readOnly/></label><label>Ticker<input value="INSTARA" readOnly/></label></div>
 <label className="form-label">Description<textarea rows={3} maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="form-label">Coin image URL<input type="url" required placeholder="https://…/instara.png" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/></label><label className="form-label">Permanent metadata URI<input type="url" required placeholder="https://…/instara.json" value={form.metadataUri} onChange={e=>setForm({...form,metadataUri:e.target.value})}/></label>
 <div className="fee-note"><Coins size={20}/><div><strong>All creator fees go to the dev wallet.</strong><p>2% trading fee. Meteora takes its protocol share; the remaining creator fees belong to your wallet. No Instagram verification or buyback deduction applies to the main token.</p></div></div>
 {state.token?.status==='launched'?<div className="notice"><span>Main token launched.</span></div>:<button className="primary-button" type="submit" disabled={busy||!!pending||state.token?.status==='pending'||!!state.configuredMint||!state.enabled||!state.meteoraConfig}><Rocket size={16}/>{busy?'Preparing…':'Launch main token'}</button>}
 {state.token?.status==='pending'&&!pending&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>recover()}>Recover expired launch</button>}
 </form></section><aside><section className="panel admin-details">{state.meteoraConfig&&<><h3>Launch configuration</h3><code>{state.meteoraConfig}</code><p>Saved automatically. No environment key needed.</p></>}<h3>Dev fee recipient</h3><code>{state.wallet}</code><p>This signed wallet is the Meteora creator and fee recipient.</p>{!provider&&<div className="form-actions"><button className="secondary-button" disabled={busy} onClick={()=>connect('phantom')}>Reconnect Phantom</button><button className="secondary-button" disabled={busy} onClick={()=>connect('solflare')}>Reconnect Solflare</button></div>}
 {pending&&<button className="primary-button" disabled={busy} onClick={()=>confirm()}>Check confirmation</button>}
 {state.token?.status==='launched'&&<><h3>INSTARA mint</h3><code>{state.token.mint}</code><a href={`https://solscan.io/token/${state.token.mint}`} target="_blank" rel="noreferrer">View on Solscan <ExternalLink size={14}/></a><p>This mint is saved automatically for community buybacks.</p><button className="primary-button" disabled={busy||!!pending} onClick={()=>transact('claim')}><Coins size={16}/> Claim dev fees</button></>}
 {state.configuredMint&&!state.lookupTables&&<><h3>Set up creator claims</h3><p>Create the shared transaction lookup table. Its address is saved automatically.</p><button className="secondary-button" disabled={busy||!!state.pendingConfig} onClick={()=>transact('lookup')}>Prepare creator claims</button>{state.pendingConfig?.kind==='main_lookup'&&!pending&&<button className="secondary-button" disabled={busy} onClick={()=>recover(true)}>Recover expired setup</button>}</>}<p>Only one main token can be launched through this page.</p>{busy&&<LoaderCircle className="spin" size={18}/>}</section></aside></div>}
 </main></div>;
}
