import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {verificationWrites,recipientWrites} from '../lib/bio-store';
import {assertRecipient,assertClaim} from '../lib/domain';
test('bio consumption is single-use and claimed badge follows immutable identity across handle reuse',()=>{
 const db=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(`drizzle/${file}`,'utf8'));
 const now=Date.now(),code='INSTARA-0123456789abcdef0123456789abcdef';
 const c={id:'proof1',account_id:'instagram-public:123',username:'creator',code,expires_at:now+10000,phase:'checking',wallet:'w1',session_hash:'s1'};
 db.prepare('INSERT INTO sessions(token_hash,wallet,expires_at) VALUES(?,?,?)').run('s1','w1',now+100000);
 const put=db.prepare('INSERT INTO bio_challenges(id,session_hash,wallet,username,account_id,code,expires_at,phase,created_at) VALUES(?,?,?,?,?,?,?,?,?)');
 put.run(c.id,c.session_hash,c.wallet,c.username,c.account_id,c.code,c.expires_at,c.phase,now);
 const profile={id:c.account_id,username:c.username,biography:code,followers:100,picture:null,name:'Creator'};
 for(const w of recipientWrites(profile,now))db.prepare(w.sql).run(...w.args);
 const unclaimed=db.prepare('SELECT * FROM creators WHERE id=?').get(profile.id)!;
 assert.equal(unclaimed.claimed_at,null);assert.equal(unclaimed.verified_at,0);
 assert.doesNotThrow(()=>assertRecipient({id:profile.id,username:profile.username,profile_at:Number(unclaimed.profile_at)},profile.username,profile.id,now));
 assert.throws(()=>assertClaim({creator_id:null,verified_at:null},{creator_id:profile.id},now));
 const writes=verificationWrites(c,profile,{wallet:c.wallet,token_hash:c.session_hash},now);
 const commit=()=>{db.exec('BEGIN');for(const w of writes)db.prepare(w.sql).run(...w.args);db.exec('COMMIT');};commit();
 assert.equal(db.prepare('SELECT claimed_at FROM creators WHERE id=?').get(profile.id)?.claimed_at,now);
 assert.equal(db.prepare('SELECT phase FROM bio_challenges WHERE id=?').get(c.id)?.phase,'verified');
 for(const w of recipientWrites(profile,now+2))db.prepare(w.sql).run(...w.args);
 assert.equal(db.prepare('SELECT claimed_at FROM creators WHERE id=?').get(profile.id)?.claimed_at,now);
 db.prepare('UPDATE sessions SET creator_id=NULL WHERE token_hash=?').run('s1');commit();assert.equal(db.prepare('SELECT creator_id FROM sessions WHERE token_hash=?').get('s1')?.creator_id,null);
 db.prepare("INSERT INTO tokens(id,wallet,name,symbol,description,handle,creator_id,image,metadata_uri,status,created_at) VALUES('coin1','w1','Coin','COIN','','creator',?,'','','launched',?)").run(profile.id,now);
 const newer={...c,id:'proof2',account_id:'instagram-public:999'};put.run(newer.id,newer.session_hash,newer.wallet,newer.username,newer.account_id,newer.code,newer.expires_at,newer.phase,now+1);
 db.exec('BEGIN');for(const w of verificationWrites(newer,{...profile,id:newer.account_id},{wallet:'w1',token_hash:'s1'},now+1))db.prepare(w.sql).run(...w.args);db.exec('COMMIT');
 const coin=db.prepare("SELECT tokens.creator_id,creators.claimed_at FROM tokens LEFT JOIN creators ON creators.id=tokens.creator_id WHERE tokens.id='coin1'").get();assert.equal(coin?.creator_id,profile.id);assert.equal(coin?.claimed_at,now);
 assert.equal(db.prepare('SELECT id FROM creators WHERE username=?').get('creator')?.id,newer.account_id);
 db.close();
});
