import { test } from "node:test";
import assert from "node:assert/strict";
import { Keypair, PublicKey } from "@solana/web3.js";
import nacl from "tweetnacl";
import { assertClaim, assertRecipient, draftSchema, verifyWallet } from "../lib/domain";
test("signed challenge is bound to its wallet and exact message",()=>{const k=Keypair.generate(),m="Instara: nonce 123 at https://example.com";const sig=Array.from(nacl.sign.detached(new TextEncoder().encode(m),k.secretKey));assert.ok(verifyWallet(m,sig,k.publicKey.toBase58()));assert.equal(verifyWallet(m+"x",sig,k.publicKey.toBase58()),false);assert.equal(verifyWallet(m,sig,Keypair.generate().publicKey.toBase58()),false);});
test("nonexistent, stale and recycled handles cannot be launched",()=>{const now=Date.now(),c={id:"123",username:"creator",profile_at:now};assert.throws(()=>assertRecipient(null,"creator",null,now));assert.throws(()=>assertRecipient({...c,profile_at:now-1000000},"creator","123",now));assert.throws(()=>assertRecipient({...c,id:"456"},"creator","123",now));assert.doesNotThrow(()=>assertRecipient(c,"creator","123",now));});
test("claim authorization follows permanent ID, not matching username",()=>{const now=Date.now();assert.throws(()=>assertClaim({creator_id:"other",verified_at:now},{creator_id:"123"},now));assert.throws(()=>assertClaim({creator_id:"123",verified_at:now-1000000},{creator_id:"123"},now));assert.doesNotThrow(()=>assertClaim({creator_id:"123",verified_at:now},{creator_id:"123"},now));});
test("draft inputs reject script URLs and oversized UTF8 names",()=>{const d={name:"Coin",symbol:"COIN",handle:"@Creator",description:"",image:"https://example.com/c.png",metadataUri:""};assert.equal(draftSchema.parse(d).handle,"creator");assert.throws(()=>draftSchema.parse({...d,image:"javascript:alert(1)"}));assert.throws(()=>draftSchema.parse({...d,name:"🚀".repeat(16)}));});
