"use client";
import { useEffect, useState } from "react";
import { CurveSummary, MarketChart } from "@/components/market";
import { Camera as Instagram, Wallet, LockKeyhole, Rocket, Compass, CircleHelp, ShieldCheck, Check, Plus, ExternalLink, X, ChevronRight, Copy, LoaderCircle, Search, Coins, Layers } from "lucide-react";

type Creator = { id: string; username: string };
type Token = { id: string; name: string; symbol: string; description: string; handle: string; creator_id: string | null; image: string; metadata_uri: string; status: string; mint: string | null };
type Status = { live: boolean; instagram: boolean };
type Provider = { connect(): Promise<{ publicKey: { toString(): string } }>; disconnect(): Promise<void>; signMessage(message: Uint8Array, encoding?: string): Promise<{ signature: Uint8Array }>; signTransaction(transaction: any): Promise<any> };
declare global { interface Window { phantom?: { solana?: Provider }; solflare?: Provider } }
async function api(path: string, body?: unknown) {
  const r = await fetch(`/api/${path}`, { method: body === undefined ? "GET" : "POST", headers: body === undefined ? {} : { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
  const data = await r.json() as Record<string, any>; if (!r.ok) throw new Error(data.error || "Unable to complete this request. Please try again."); return data;
}
const short = (s: string) => `${s.slice(0, 4)}…${s.slice(-4)}`;
export default function Home() {
  const [tab, setTab] = useState("launch"), [wallet, setWallet] = useState(""), [provider, setProvider] = useState<Provider | null>(null);
  const [modal, setModal] = useState(false), [busy, setBusy] = useState(""), [notice, setNotice] = useState<{ text: string; error?: boolean } | null>(null);
  const [status, setStatus] = useState<Status>({ live: false, instagram: false });
  const [creators, setCreators] = useState<Creator[]>([]), [tokens, setTokens] = useState<Token[]>([]), [drafts, setDrafts] = useState<Token[]>([]), [identity, setIdentity] = useState<Creator | null>(null);
  const [chart, setChart] = useState<Token | null>(null);
  const [query, setQuery] = useState(""), [draftId, setDraftId] = useState(""), [consent, setConsent] = useState(false);
  const [form, setForm] = useState({ name: "", symbol: "", handle: "", description: "", image: "", metadataUri: "" });
  const [pending, setPending] = useState<{ signature: string; intentId: string } | null>(null);
  const recipient = creators.find(c => c.username.toLowerCase() === form.handle.replace(/^@/, "").toLowerCase());
  const fail = (e: unknown) => setNotice({ text: e instanceof Error ? e.message : "Please try again.", error: true });
  async function refresh() { try { const d = await api("state"); setStatus(d.status); setCreators(d.creators); setTokens(d.tokens); setDrafts(d.drafts); setWallet(d.wallet || ""); setIdentity(d.identity); setPending(d.pending || null); } catch (e) { fail(e); } }
  useEffect(() => { void refresh(); const url = new URL(window.location.href); const msg = url.searchParams.get("message"); if (msg) { setNotice({ text: msg, error: url.searchParams.has("error") }); setTab("claim"); history.replaceState({}, "", "/"); } }, []);
  useEffect(() => { if (!modal) return; const handler = (e: KeyboardEvent) => { if (e.key === "Escape") setModal(false); if (e.key === "Tab") { const items = Array.from(document.querySelectorAll<HTMLElement>('[role="dialog"] button:not(:disabled), [role="dialog"] a[href]')); const first = items[0], last = items.at(-1); if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [modal]);
  async function connect(type: "phantom" | "solflare") {
    const p = type === "phantom" ? window.phantom?.solana : window.solflare;
    if (!p) return setNotice({ text: `${type === "phantom" ? "Phantom" : "Solflare"} isn’t installed. Open Fanfare in your wallet browser or install the extension.`, error: true });
    setBusy("wallet"); try { const result = await p.connect(); const c = await api("wallet/challenge", { wallet: result.publicKey.toString() }); const signed = await p.signMessage(new TextEncoder().encode(c.message), "utf8"); await api("wallet/verify", { id: c.id, signature: Array.from(signed.signature) }); setProvider(p); setModal(false); await refresh(); setNotice({ text: "Wallet connected. No funds were transferred." }); } catch (e) { fail(e); } finally { setBusy(""); }
  }
  async function saveDraft() { if (!wallet) return setModal(true); setBusy("save"); try { const d = await api("drafts", { ...form, id: draftId || undefined }); setDraftId(d.id); await refresh(); setNotice({ text: "Draft saved. No token has been created yet." }); } catch (e) { fail(e); } finally { setBusy(""); } }
  async function confirm(value = pending) { if (!value) return; setBusy("confirm"); try { const d = await api("launch/confirm", value); setPending(null); await refresh(); setTab(d.kind === "claim" ? "claim" : "explore"); setNotice({ text: d.kind === "claim" ? "Claim confirmed on Solana." : "Launch confirmed on Solana. Your coin is now listed." }); } catch (e) { fail(e); } finally { setBusy(""); } }
  async function transact(kind: "launch" | "claim", id?: string) {
    if (!status.live) return setNotice({ text: kind === "launch" ? "Launching is currently unavailable. You can save your coin as a draft." : "Fee claims are currently unavailable. Please try again later.", error: true });
    if (!wallet || !provider) return setModal(true); setBusy(kind);
    try { let target = id; if (kind === "launch") { const draft = await api("drafts", { ...form, id: draftId || undefined }); setDraftId(draft.id); target = draft.id; }
      const p = await api(`${kind}/prepare`, { id: target }); const { Transaction } = await import("@solana/web3.js");
      const signed = await provider.signTransaction(Transaction.from(Uint8Array.from(atob(p.transaction), c => c.charCodeAt(0))));
      const sent = await api("launch/submit", { intentId: p.intentId, transaction: btoa(String.fromCharCode(...signed.serialize())) });
      const pendingTx = { signature: sent.signature, intentId: p.intentId }; setPending(pendingTx); setNotice({ text: "Transaction submitted. Check confirmation in a moment." }); await confirm(pendingTx);
    } catch (e) { fail(e); } finally { setBusy(""); }
  }
  const field = (key: keyof typeof form, value: string) => setForm(f => ({ ...f, [key]: value }));
  return <div className="app-shell">
    <header><a className="brand" href="/" aria-label="Fanfare home"><img src="/fanfare-logo.png" alt="" width="40" height="40" />fan<span>fare</span></a><nav aria-label="Main navigation">{[{ id: "launch", text: "Launch", icon: Rocket }, { id: "explore", text: "Explore", icon: Compass }, { id: "claim", text: "Claim fees", icon: Coins }].map(n => <button key={n.id} className={tab === n.id ? "nav-active" : ""} onClick={() => setTab(n.id)}><n.icon size={16} />{n.text}</button>)}</nav><button className="wallet-button" onClick={() => setModal(true)}><Wallet size={16} />{wallet ? short(wallet) : "Connect wallet"}</button></header>
    <main>{notice && <div role="status" className={`notice ${notice.error ? "error" : ""}`}><span>{notice.text}</span><button aria-label="Dismiss notification" onClick={() => setNotice(null)}><X size={16} /></button></div>}{pending && <div className="notice"><span>A transaction is awaiting confirmation.</span><button onClick={() => confirm()} disabled={!!busy}>Check confirmation</button></div>}
      {tab === "launch" && <><div className="page-heading"><div className="eyebrow"><Instagram size={14} /> THE INSTAGRAM CREATOR LAUNCHPAD</div><h1>Their community.<br /> Their coin. <span>Their fees.</span></h1><p>Launch for an existing Instagram creator. Put the creator fees in their hands.</p></div>
      <CurveSummary /><div className="launch-grid"><section className="panel"><div className="panel-heading"><div><span className="step-number">01</span><h2>Create your coin</h2></div><span className="solana-label"><Layers size={14} /> Meteora · 2% fee</span></div><form onSubmit={e => { e.preventDefault(); void saveDraft(); }}>
      <label className="section-label" htmlFor="handle">Who are you launching for?</label><div className="handle-input"><Instagram size={20} /><span>@</span><input id="handle" list="creators" autoComplete="off" required placeholder="instagram_handle" maxLength={30} value={form.handle} onChange={e => field("handle", e.target.value.replace(/^@/, ""))} /><span className="input-tag">Fee recipient</span></div><datalist id="creators">{creators.map(c => <option key={c.id} value={c.username} />)}</datalist><p className={`field-hint ${recipient ? "verified-text" : ""}`}>{recipient ? <><ShieldCheck size={14} /> Existing account verified. Recipient ID locked at launch.</> : <><LockKeyhole size={13} /> Account must exist and be verified before launch. No rerouting.</>}</p><div className="form-rule" />
      <div className="two-fields"><label>Coin name<input required maxLength={32} placeholder="e.g. The daily edit" value={form.name} onChange={e => field("name", e.target.value)} /></label><label>Ticker<div className="ticker-input"><span>$</span><input required pattern="[A-Za-z0-9]{1,10}" maxLength={10} placeholder="EDIT" value={form.symbol} onChange={e => field("symbol", e.target.value.toUpperCase())} /></div></label></div>
      <label className="form-label">Description <span>Optional</span><textarea rows={3} maxLength={500} placeholder="Tell the community what this coin is about…" value={form.description} onChange={e => field("description", e.target.value)} /></label>
      <label className="form-label">Coin image URL <span>HTTPS</span><input type="url" placeholder="https://…/coin.png" value={form.image} onChange={e => field("image", e.target.value)} /></label>
      <details className="advanced"><summary>Token metadata <span>Required to launch</span></summary><label className="form-label">Permanent metadata URI<input type="url" placeholder="https://…/metadata.json" value={form.metadataUri} onChange={e => field("metadataUri", e.target.value)} /></label><p>Use a public, permanent JSON URI with this coin’s name, symbol, description, and image.</p></details>
      <div className="fee-note"><LockKeyhole size={20} /><div><strong>Creator fees stay with the creator.</strong><p>2% trading fee. The creator receives the non-protocol share through their vault. Network fees are separate.</p></div></div>
      <label className="checkbox-label"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} /><span>I understand launching a coin does not imply the creator’s endorsement.</span></label>
      <div className="form-actions"><button className="secondary-button" type="submit" disabled={!!busy}>{busy === "save" && <LoaderCircle className="spin" size={16} />}Save draft</button><button className="primary-button" type="button" disabled={!!busy || !!pending || (!!wallet && (!recipient || !consent || !form.name || !form.symbol || !form.metadataUri))} onClick={() => wallet ? transact("launch") : setModal(true)}><Rocket size={16} />{!wallet ? "Connect wallet to launch" : busy === "launch" ? "Preparing…" : "Launch coin"}</button></div><p className="bottom-hint">Review the transaction in your wallet before signing.</p>
      </form></section><aside><div className="preview-label">COIN PREVIEW <span>Made for your community</span></div><div className="coin-preview"><div className="preview-cover"><div className="cover-grid" /><span className="preview-chip"><LockKeyhole size={12} /> Creator fees protected</span><div className="coin-avatar">{form.image && /^https:\/\//.test(form.image) ? <img key={form.image} src={form.image} referrerPolicy="no-referrer" alt="Coin" /> : <Instagram size={32} />}</div></div><div className="preview-body"><div className="coin-title"><h3>{form.name || "Your next big idea"}</h3><span>${form.symbol || "TICKER"}</span></div><p className="preview-description">{form.description || "A coin for the people who make your feed worth following."}</p><div className="recipient-row"><span className="recipient-avatar"><Instagram size={19} /></span><div><small>Creator fee recipient</small><strong>@{form.handle || "yourcreator"}</strong></div><LockKeyhole size={17} /></div><div className="preview-stats"><div><span>Creator allocation</span><strong>100% <small>of creator fees</small></strong></div><span className="locked-badge">Locked vault</span></div></div></div>
      <div className="how-card"><h3>A better kind of fan support.</h3>{[{ title: "You launch", text: "Create a coin for an existing, verified Instagram account." }, { title: "The community trades", text: "Creator fees accumulate in an on-chain vault." }, { title: "The creator claims", text: "Instagram verification + a wallet signature unlock the payout." }].map((s, i) => <div className="how-step" key={s.title}><span>{i + 1}</span><div><strong>{s.title}</strong><p>{s.text}</p></div></div>)}<button onClick={() => setTab("how")}><CircleHelp size={15} /> Understand the fee flow</button></div><div className="powered"><ShieldCheck size={16} /> Account-bound fees. Wallet-approved transactions.</div></aside></div></>}
      {tab === "explore" && <><div className="section-heading"><div><div className="eyebrow">THE COMMUNITY BOARD</div><h1>Explore coins</h1><p>Confirmed launches with an Instagram creator at the center.</p></div><button className="primary-button" onClick={() => setTab("launch")}><Plus size={17} />Launch a coin</button></div><div className="search"><Search size={18} /><input aria-label="Search coins" placeholder="Search coin, ticker, or creator" value={query} onChange={e => setQuery(e.target.value)} /></div>{chart?.mint && <MarketChart token={{...chart,mint:chart.mint}} onClose={() => setChart(null)} />}<div className="token-grid">{tokens.filter(t => `${t.name} ${t.symbol} ${t.handle}`.toLowerCase().includes(query.toLowerCase())).map(t => <article className="panel token-card" key={t.id}><span className="token-letter">{t.symbol.slice(0, 2)}</span><button onClick={() => setChart(t)}><h3>{t.name} <small>${t.symbol}</small></h3></button><p>{t.description}</p><div className="recipient-row"><Instagram size={18} />@{t.handle}<span className="locked-badge">Vault linked</span></div><a href={`https://gmgn.ai/sol/token/${t.mint}`} target="_blank" rel="noreferrer">View on GMGN <ExternalLink size={14} /></a><button className="secondary-button chart-button" onClick={() => setChart(t)}>Price chart</button></article>)}</div>{!tokens.length && <div className="empty-state"><span><Compass size={32} /></span><h2>The first chapter is yours.</h2><p>No confirmed launches yet. Set up a coin and bring your community along.</p><button className="secondary-button" onClick={() => setTab("launch")}>Create a coin</button></div>}{tokens.length > 0 && !tokens.some(t => `${t.name} ${t.symbol} ${t.handle}`.toLowerCase().includes(query.toLowerCase())) && <div className="empty-state"><h2>No matching coins</h2><button onClick={() => setQuery("")}>Clear search</button></div>}{drafts.length > 0 && <section className="draft-section"><h2>Your saved drafts</h2>{drafts.map(d => <button className="draft-row" key={d.id} onClick={async () => { if(d.status === "pending") { try { await api("launch/recover", {id:d.id}); await refresh(); setNotice({text:"Expired launch recovered. Your draft can be edited again."}); } catch(e) { fail(e); } return; } setForm({ name: d.name, symbol: d.symbol, description: d.description, handle: d.handle, image: d.image, metadataUri: d.metadata_uri }); setDraftId(d.id); setTab("launch"); }}><span>{d.name}<small>${d.symbol} · @{d.handle}</small></span><span>{d.status === "pending" ? "Recover expired launch" : "Edit draft"} <ChevronRight size={15} /></span></button>)}</section>}</>}
      {tab === "claim" && <><div className="section-heading"><div><div className="eyebrow">FOR THE PEOPLE BEHIND THE PROFILE</div><h1>Your account. Your earnings.</h1><p>Verify your existing Instagram account to claim its creator fees.</p></div></div><div className="claim-grid"><section className="panel claim-panel"><span className="large-instagram"><Instagram size={32} /></span><h2>Make it official.</h2><p>Link your Instagram professional account and a Solana wallet. Your Instagram password is only entered on Instagram.</p><div className="claim-step"><span className={wallet ? "done" : ""}>{wallet ? <Check size={16} /> : "1"}</span><div><strong>Connect your payout wallet</strong><small>{wallet ? short(wallet) : "Prove ownership with a message signature."}</small></div><button className="secondary-button" onClick={() => setModal(true)}>{wallet ? "Connected" : "Connect"}</button></div><div className="claim-step"><span className={identity ? "done" : ""}>{identity ? <Check size={16} /> : "2"}</span><div><strong>Verify Instagram</strong><small>{identity ? `@${identity.username} verified` : "For Instagram business and creator accounts."}</small></div>{wallet && status.instagram ? <a className="secondary-button" href="/api/instagram/start">{identity ? "Refresh" : "Verify"}</a> : <button className="secondary-button" onClick={() => !wallet ? setModal(true) : setNotice({ text: "Instagram verification is currently unavailable. Please try again later.", error: true })}>Verify</button>}</div><div className="fee-note"><ShieldCheck size={19} /><p>Fees follow your permanent account ID, even if your handle changes. Nonexistent accounts cannot receive fees.</p></div></section><section className="panel earnings-panel"><div className="panel-heading"><h2>Your fee vaults</h2><LockKeyhole size={18} /></div>{identity && tokens.filter(t => t.creator_id === identity.id).length > 0 ? tokens.filter(t => t.creator_id === identity.id).map(t => <div className="draft-row" key={t.id}><span>{t.name}<small>${t.symbol}</small></span><button className="primary-button" disabled={!!busy || !!pending} onClick={() => transact("claim", t.id)}>Claim fees</button></div>) : <div className="empty-state compact"><LockKeyhole size={30} /><h3>{identity ? "No fee vaults yet" : "Your vaults will appear here"}</h3><p>{identity ? "Coins launched for your verified account will appear here." : "Connect and verify your account to find your creator fees."}</p></div>}</section></div></>}
      {tab === "how" && <><div className="section-heading"><div><div className="eyebrow">FOLLOW THE FEES</div><h1>Built around the creator.</h1><p>A transparent path from a community trade to a creator’s wallet.</p></div></div><div className="flow-grid">{[{ icon: Rocket, title: "01 / Launch", text: "Choose an existing, verified Instagram account. The token’s creator address is a vault permanently bound to that account ID." }, { icon: LockKeyhole, title: "02 / Accumulate", text: "Meteora’s creator-fee portion accrues to the vault. The launcher has no withdrawal permission. Trading fees are fixed at 2%." }, { icon: Instagram, title: "03 / Verify", text: "The account owner verifies through Instagram and signs with a Solana wallet. Our verification service authorizes the claim." }, { icon: Wallet, title: "04 / Claim", text: "The escrow checks both signatures and pays the wallet. A missing or deleted Instagram account cannot be replaced with a different recipient." }].map(c => <div className="panel flow-card" key={c.title}><c.icon size={25} /><h2>{c.title}</h2><p>{c.text}</p></div>)}</div><div className="panel trust-note"><h2>What you’re trusting</h2><p>Our verification service connects a Meta-confirmed account ID to a wallet. Its signing authority is a trust point. Account verification does not mean a creator endorses a community coin.</p><p>The account owner must verify their existing account before launch. Arbitrary handles and unverified accounts cannot receive fees. Instagram verification supports Creator and Business accounts.</p><a href="https://github.com/MeteoraAg/dynamic-bonding-curve" target="_blank" rel="noreferrer">Meteora protocol documentation <ExternalLink size={14} /></a></div></>}
    </main><footer><span className="footer-brand">fanfare <span>© 2026</span></span><span>Independent project. Not affiliated with Instagram, Meta, or Meteora.</span><button onClick={() => setTab("how")}>How it works <ExternalLink size={12} /></button></footer>
    {modal && <div className="modal-backdrop" onClick={() => setModal(false)}><section className="wallet-modal" role="dialog" aria-modal="true" aria-labelledby="wallet-title" onClick={e => e.stopPropagation()}><button className="modal-close" autoFocus aria-label="Close wallet dialog" onClick={() => setModal(false)}><X size={20} /></button><span className="large-instagram"><Wallet size={26} /></span><h2 id="wallet-title">{wallet ? "Your wallet" : "Connect your wallet"}</h2><p>Sign a message to prove ownership. Your keys stay in your wallet.</p>{wallet && <div className="connected-address"><span>{short(wallet)}</span><button aria-label="Copy wallet address" onClick={() => navigator.clipboard.writeText(wallet).then(() => setNotice({ text: "Wallet address copied." })).catch(fail)}><Copy size={16} /></button></div>}<button className="provider-button" disabled={!!busy} onClick={() => connect("phantom")}><span className="provider-icon phantom">P</span>Phantom<ChevronRight size={17} /></button><button className="provider-button" disabled={!!busy} onClick={() => connect("solflare")}><span className="provider-icon solflare">S</span>Solflare<ChevronRight size={17} /></button>{wallet && <button className="disconnect" onClick={async () => { try { await api("wallet/logout", {}); await provider?.disconnect(); setProvider(null); setWallet(""); setIdentity(null); setModal(false); await refresh(); } catch (e) { fail(e); } }}>Disconnect wallet</button>}<p className="bottom-hint">Use the wallet’s in-app browser on mobile.</p></section></div>}
  </div>;
}
