"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, Check, Copy, ExternalLink, LoaderCircle, ShieldCheck } from "lucide-react";
type Profile={username:string;name:string;followers:number|null;biography:string;picture:string|null};
type Challenge={id:string;username:string;code:string|null;expiresAt:number;phase:string;profile:Profile|null;error:string|null};
type Identity={id:string;username:string;followers?:number|null;biography?:string|null;picture?:string|null};
async function request(path:string,body:unknown={}){const r=await fetch(`/api/bio/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string;challenge:Challenge|null};if(!r.ok)throw new Error(d.error||'Please try again.');return d.challenge;}
export function BioVerification({wallet,identity,onConnect,onVerified}:{wallet:string;identity:Identity|null;onConnect:()=>void;onVerified:()=>Promise<void>}){
  const [username,setUsername]=useState(''),[challenge,setChallenge]=useState<Challenge|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
  const notified=useRef(''),callback=useRef(onVerified);callback.current=onVerified;
  const pending=!!challenge&&['starting','resolving','starting_check','checking'].includes(challenge.phase);
  useEffect(()=>{let alive=true;setChallenge(null);setError('');if(wallet)request('status').then(c=>{if(alive){setChallenge(c);if(c)setUsername(c.username);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[wallet]);
  useEffect(()=>{if(!wallet||!pending)return;let alive=true;const timer=setInterval(()=>{request('status').then(c=>{if(alive)setChallenge(c);}).catch(e=>{if(alive)setError(e.message);});},5000);return()=>{alive=false;clearInterval(timer);};},[wallet,pending,challenge?.id]);
  useEffect(()=>{if(challenge?.phase==='verified'&&notified.current!==challenge.id){notified.current=challenge.id;void callback.current();}},[challenge?.id,challenge?.phase]);
  async function act(path:'start'|'check'){if(!wallet)return onConnect();setBusy(true);setError('');setCopied(false);try{setChallenge(await request(path,path==='start'?{username}:{id:challenge?.id}));}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
  const complete=challenge?.phase==='verified';
  return <section className="panel claim-panel"><span className="large-instagram"><Camera size={32}/></span><h2>Your bio is your proof.</h2><p>Add a one-time code to your public Instagram bio. We’ll check it and connect that account to your payout wallet.</p>
    <div className="claim-step"><span className={wallet?'done':''}>{wallet?<Check size={16}/>:'1'}</span><div><strong>Connect your payout wallet</strong><small>{wallet?`${wallet.slice(0,4)}…${wallet.slice(-4)}`:'Sign a message to prove wallet ownership.'}</small></div><button className="secondary-button" onClick={onConnect}>{wallet?'Connected':'Connect'}</button></div>
    <form className="bio-form" onSubmit={e=>{e.preventDefault();void act('start');}}><label className="form-label" htmlFor="verify-handle">Your Instagram handle<div className="handle-input"><span>@</span><input id="verify-handle" autoComplete="off" placeholder="your_handle" pattern="[A-Za-z0-9._]{1,30}" maxLength={30} required value={username} onChange={e=>setUsername(e.target.value.replace(/^@/,''))}/></div></label><button type="submit" className="secondary-button" disabled={busy||pending}>{busy||pending?<LoaderCircle className="spin" size={15}/>:<ShieldCheck size={15}/>}Generate verification code</button></form>
    {pending&&<p className="bio-progress" role="status"><LoaderCircle className="spin" size={16}/>{challenge?.phase==='checking'||challenge?.phase==='starting_check'?'Checking your latest bio…':'Finding your Instagram account…'}</p>}
    {challenge?.code&&<div className="bio-code-panel"><strong>2. Add this code to @{challenge.username}’s bio</strong><div className="bio-code"><code>{challenge.code}</code><button aria-label="Copy verification code" onClick={()=>navigator.clipboard.writeText(challenge.code!).then(()=>setCopied(true)).catch(()=>setError('Copy the displayed code manually.'))}>{copied?<Check size={17}/>:<Copy size={17}/>}</button></div><p>Use only a code you generated here with your own wallet. Expires at {new Date(challenge.expiresAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}.</p><a href={`https://www.instagram.com/${encodeURIComponent(challenge.username)}/`} target="_blank" rel="noreferrer">Open Instagram <ExternalLink size={13}/></a><button className="primary-button" disabled={busy||pending} onClick={()=>act('check')}>I’ve added it — verify bio</button></div>}
    {complete&&<div className="bio-success" role="status"><ShieldCheck size={20}/><div><strong>@{challenge.username} verified</strong><p>You can remove the code from your bio now. Claim within 15 minutes, or verify again.</p></div></div>}
    {challenge?.phase==='expired'&&<p className="field-hint">Your code expired. Generate a new one.</p>}
    {(error||challenge?.error)&&<p className="bio-error" role="alert">{error||challenge?.error}</p>}
    {(complete?challenge.profile:identity)&&<div className="verified-profile"><strong>@{(complete?challenge.profile:identity)?.username}</strong>{(complete?challenge.profile:identity)?.followers!=null&&<span>{(complete?challenge.profile:identity)!.followers!.toLocaleString()} followers</span>}<p>{(complete?challenge.profile:identity)?.biography}</p></div>}
    <div className="fee-note"><ShieldCheck size={19}/><p>Fees follow your account ID, even if your handle changes. Public accounts only. A missing or unreadable profile cannot be verified.</p></div>
  </section>;
}
