"use client";
import {useEffect,useState} from 'react';
import {BadgeCheck,LockKeyhole,Wallet} from 'lucide-react';
import {usd} from './market';
type Amount={usd:number|null;lamports:string|null};
type Fees={accountStatus:'dev'|'claimed'|'unclaimed';generated:Amount;available:Amount;claimed:Amount;paid:Amount;buyback:Amount;pendingClaims:number;chainAvailable:boolean;priceAvailable:boolean;priceStale:boolean;asOf:number};
export function TokenFees({id,isDev,claimedAt}:{id:string;isDev:boolean;claimedAt?:number|null}){
 const [fees,setFees]=useState<Fees|null>(null),[error,setError]=useState(false);
 useEffect(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;const controller=new AbortController();
  async function run(){try{const r=await fetch(`/api/fees/${id}`,{signal:controller.signal});if(!r.ok)throw new Error();const d=await r.json() as {fees:Fees};if(!stopped){setFees(d.fees);setError(false);}}catch{if(!stopped)setError(true);}finally{if(!stopped)timer=setTimeout(run,20000);}}
  void run();return()=>{stopped=true;clearTimeout(timer);controller.abort();};
 },[id]);
 const status=fees?.accountStatus||(isDev?'dev':claimedAt?'claimed':'unclaimed'),Icon=status==='dev'?Wallet:status==='claimed'?BadgeCheck:LockKeyhole;
 const cards=[['Total creator fees',fees?.generated,'After Meteora’s protocol share'],['Available on Meteora',fees?.available,'Accrued fees not yet collected'],['Fees claimed',fees?.claimed,isDev?'Collected by the dev wallet':'Completed claims, including buybacks'],[isDev?'Paid to dev wallet':'Paid to creator',fees?.paid,isDev?'100% of creator fees':'90% of each completed claim']] as const;
 return <section className="panel token-fees"><div className="panel-heading"><h2>Creator fees</h2><span className={status==='claimed'?'claimed-badge':'locked-badge'}><Icon size={14}/>{status==='dev'?'Dev wallet':status==='claimed'?'Claimed':'Unclaimed'}</span></div><p className="chart-note">{status==='dev'?'This coin’s fee recipient is the Instara dev wallet.':status==='claimed'?'The Instagram owner has verified and claimed this account.':'The Instagram owner has not claimed this account yet. Fees remain reserved for them.'}</p><div className="fee-stats">{cards.map(([label,value,hint])=><div key={label}><span>{label}</span><strong>{value?.usd!=null?value.usd>0&&value.usd<.01?'< $0.01':usd(value.usd):'—'}</strong><small>{hint}</small></div>)}</div>{!isDev&&<p className="chart-note">Used for INSTARA buyback &amp; burn: <strong>{fees?.buyback.usd!=null?usd(fees.buyback.usd):'—'}</strong>. Only completed payouts count as claimed; collecting fees into custody does not count as a creator payout.</p>}{!!fees?.pendingClaims&&<p className="chart-note">A creator payout is processing. Totals update after completion.</p>}<p className="chart-note">{error?'Fee updates are temporarily unavailable. Displayed values may be out of date.':!fees?'Loading fees…':!fees.chainAvailable?'Live pool fees are temporarily unavailable.':!fees.priceAvailable?'USD conversion is temporarily unavailable.':fees.priceStale?'USD conversion is stale; values are indicative.':'USD estimates use the current SOL price, including past claims. Updates automatically.'}</p><a className="secondary-button" href={isDev?'/admin':'/?tab=claim'}>{isDev?'Manage dev fees':status==='claimed'?'Claim creator fees':'Verify and claim account'}</a></section>;
}
