"use client";
import {useState} from 'react';
import {ArrowLeft,Copy,ExternalLink,Globe,Camera,Wallet} from 'lucide-react';
import {MarketChart} from './market';
import {TokenFees} from './token-fees';
import {ClaimedBadge} from './claimed-badge';
export type PublicToken={id:string;mint:string;name:string;symbol:string;description:string;image:string;handle:string;recipient_type:string;claimed_at?:number|null;website:string;twitter:string;telegram:string;metadata_uri:string};
export function TokenDetail({token:t}:{token:PublicToken}){
 const [message,setMessage]=useState('');async function copy(){try{await navigator.clipboard.writeText(t.mint);setMessage('Contract address copied.');}catch{setMessage('Select the contract address below to copy it.');}}
 return <div className="app-shell"><header className="token-header"><a className="brand" href="/"><img src="/brand-logo.png" width="40" height="40" alt=""/>insta<span>ra</span></a><nav><a href="/?tab=explore"><ArrowLeft size={16}/> Explore</a><a href="/">Launch a coin</a></nav><a className="wallet-button" href="/?tab=claim">Claim fees</a></header><main className="token-main"><a className="token-back" href="/?tab=explore"><ArrowLeft size={16}/> All coins</a><section className="token-hero"><div className="token-identity"><span className="token-detail-image">{t.image?<img src={t.image} alt={`${t.name} logo`}/>:t.symbol.slice(0,2)}</span><div><div className="eyebrow">{t.recipient_type==='dev'?'THE INSTARA PLATFORM TOKEN':'CREATOR COIN'}</div><h1>{t.name} <small>${t.symbol}</small></h1>{t.recipient_type==='dev'?<span className="locked-badge"><Wallet size={14}/>Dev wallet</span>:t.claimed_at?<ClaimedBadge claimedAt={t.claimed_at}/>:<span className="locked-badge">Unclaimed</span>}</div></div><div className="token-socials">{[[t.website||`/token/${t.mint}`,'Website'],[t.twitter,'X'],[t.telegram,'Telegram']].filter(([url])=>!!url).map(([url,label])=><a key={label} className="secondary-button" href={url} target="_blank" rel="noopener noreferrer"><Globe size={15}/>{label}<ExternalLink size={12}/></a>)}</div></section><div className="token-detail-grid"><div><MarketChart token={t}/><TokenFees id={t.id} isDev={t.recipient_type==='dev'} claimedAt={t.claimed_at}/></div><aside><section className="panel token-about"><h2>About {t.symbol}</h2><p>{t.description||'A community coin on Instara.'}</p><div className="recipient-row">{t.recipient_type==='dev'?<Wallet size={19}/>:<Camera size={19}/>}<div><small>Creator fee recipient</small>{t.recipient_type==='dev'?<strong>Instara dev wallet</strong>:<a href={`https://www.instagram.com/${t.handle}/`} target="_blank" rel="noopener noreferrer">@{t.handle}</a>}</div></div><div className="token-contract"><span>Contract address</span><code>{t.mint}</code><button className="secondary-button" onClick={copy}><Copy size={14}/> Copy address</button>{message&&<small role="status">{message}</small>}</div><a href={`https://solscan.io/token/${t.mint}`} target="_blank" rel="noopener noreferrer">View on Solscan <ExternalLink size={14}/></a><a className="primary-button" href={`https://gmgn.ai/sol/token/${t.mint}`} target="_blank" rel="noopener noreferrer">Trade on GMGN <ExternalLink size={15}/></a><p className="chart-note">{t.recipient_type==='dev'?'All creator fees go to the dev wallet after Meteora’s protocol share.':'Creator claims pay 90% to the verified Instagram owner and use 10% to buy and burn INSTARA. A launch or Claimed badge does not imply endorsement.'}</p></section></aside></div></main><footer><a className="brand" href="/">insta<span>ra</span></a><span>Built around creators.</span><a href="https://x.com/instaraxyz" target="_blank" rel="noopener noreferrer">@instaraxyz <ExternalLink size={14}/></a></footer></div>;
}
