import { env } from "cloudflare:workers";
import { AppError, hash } from "./domain";
export const config = () => env as unknown as Record<string, string | undefined>;
export function db() { if (!env.DB) throw new AppError("Storage is unavailable. Please try again later.", 503); return env.DB; }
export type Session = { token_hash: string; wallet: string; creator_id: string | null; verified_at: number | null; expires_at: number };
export async function session(req: Request, required = true) { const token = /(?:^|;\s*)instara_session=([^;]+)/.exec(req.headers.get("cookie") || "")?.[1]; const s = token ? await db().prepare("SELECT * FROM sessions WHERE token_hash = ? AND expires_at > ?").bind(await hash(token), Date.now()).first<Session>() : null; if (!s && required) throw new AppError("Connect your wallet first.", 401); return s; }
export function origin(req: Request) { const expected = config().APP_ORIGIN; const url = new URL(req.url); if (expected) return new URL(expected).origin; if (["localhost", "127.0.0.1"].includes(url.hostname)) return url.origin; throw new AppError("The app’s public origin is not configured.", 503); }
export function csrf(req: Request) { if (req.headers.get("origin") !== origin(req)) throw new AppError("Request origin is not allowed.", 403); }
export function json(data: unknown, status = 200, headers: Record<string, string> = {}) { return Response.json(data, { status, headers: { "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff", ...headers } }); }
export async function body(req: Request) { if (!req.headers.get("content-type")?.startsWith("application/json")) throw new AppError("Expected JSON.", 415); const reader = req.body?.getReader(); if (!reader) throw new AppError("Missing request."); const chunks: Uint8Array[] = []; let n = 0; for (;;) { const { done, value } = await reader.read(); if (done) break; n += value.length; if (n > 20000) { await reader.cancel(); throw new AppError("Request too large.", 413); } chunks.push(value); } const all = new Uint8Array(n); let offset = 0; for (const c of chunks) { all.set(c, offset); offset += c.length; } try { return JSON.parse(new TextDecoder().decode(all)); } catch { throw new AppError("Invalid JSON."); } }
export function cookie(req: Request, token: string, age = 86400) { return `instara_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${age}${origin(req).startsWith("https:") ? "; Secure" : ""}`; }
export function clientIp(req: Request) {
  if (!config().DATABASE_URL) return req.headers.get('cf-connecting-ip') || 'local';
  const hops=Number(config().TRUST_PROXY_HOPS||0), chain=(req.headers.get('x-forwarded-for')||'').split(',').map(s=>s.trim()).filter(Boolean);
  return Number.isInteger(hops)&&hops>0&&chain.length>=hops ? chain[chain.length-hops] : 'local';
}
export async function rateLimit(key: string, max = 20) { const bucket = Math.floor(Date.now() / 60000); const result = await db().prepare("INSERT INTO rate_limits (key, count, expires_at) VALUES (?, 1, ?) ON CONFLICT(key) DO UPDATE SET count = rate_limits.count + 1 RETURNING count").bind(`${key}:${bucket}`, (bucket + 2) * 60000).first<{ count: number }>(); if (!result || result.count > max) throw new AppError("Too many requests. Try again in a minute.", 429); }
export function readiness() { const e = config(); const blockers: string[] = []; const instagram = !!(e.APIFY_API_TOKEN && e.APP_ORIGIN); if (!instagram) blockers.push("Configure the Instagram profile reader."); if (!e.METEORA_CONFIG_KEY) blockers.push("Create and verify the Meteora 2% curve configuration."); if (!e.SOLANA_RPC_URL) blockers.push("Configure a Solana RPC endpoint."); if (!e.ESCROW_PROGRAM_ID || !e.VERIFIER_SECRET_KEY || !e.VERIFIER_PUBLIC_KEY) blockers.push("Deploy the escrow and configure its verification authority."); if (e.LIVE_LAUNCHES_ENABLED !== "true" || e.ESCROW_REVIEWED !== "true") blockers.push("Complete escrow review and integration testing before enabling funds."); return { live: !blockers.length, instagram, blockers, network: e.SOLANA_NETWORK === "mainnet-beta" ? "Solana mainnet" : "Network not enabled" }; }
