// Preparation only. The payer signs and submits externally. No broadcast occurs here.
import {AddressLookupTableProgram,ComputeBudgetProgram,Connection,Keypair,PublicKey,SystemProgram,Transaction} from '@solana/web3.js';
import {mkdirSync,writeFileSync} from 'node:fs';
import {buybackRoute} from '../lib/buyback';
import {initializeBuyback,buybackAddress,NATIVE_MINT,TOKEN_PROGRAM,ASSOCIATED_TOKEN_PROGRAM,vaultAddress} from '../lib/escrow';
const e=process.env;
for(const key of ['SOLANA_RPC_URL','ESCROW_PROGRAM_ID','VERIFIER_SECRET_KEY','VERIFIER_PUBLIC_KEY','DEV_WALLET_ADDRESS','INSTARA_MINT','METEORA_CONFIG_KEY'])if(!e[key])throw new Error(`Set ${key}.`);
const connection=new Connection(e.SOLANA_RPC_URL!,'confirmed'),program=new PublicKey(e.ESCROW_PROGRAM_ID!),payer=new PublicKey(e.DEV_WALLET_ADDRESS!),mint=new PublicKey(e.INSTARA_MINT!),verifier=Keypair.fromSecretKey(Uint8Array.from(JSON.parse(e.VERIFIER_SECRET_KEY!)));
if(verifier.publicKey.toBase58()!==e.VERIFIER_PUBLIC_KEY)throw new Error('Verifier mismatch.');
if(await connection.getGenesisHash()!=='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp')throw new Error('Expected mainnet RPC.');
if(await connection.getAccountInfo(buybackAddress(program)))throw new Error('Buyback policy already exists. Do not reinitialize or change the mint.');
const route=await buybackRoute(connection,e,vaultAddress(mint,program),BigInt(10000));
const slot=await connection.getSlot('finalized'),[create,table]=AddressLookupTableProgram.createLookupTable({authority:payer,payer,recentSlot:slot});
const addresses=[program,buybackAddress(program),mint,NATIVE_MINT,TOKEN_PROGRAM,ASSOCIATED_TOKEN_PROGRAM,SystemProgram.programId,ComputeBudgetProgram.programId,new PublicKey(e.METEORA_CONFIG_KEY!),route.inner.programId,...route.inner.keys.map(k=>k.pubkey)];
const unique=[...new Map(addresses.map(p=>[p.toBase58(),p])).values()];
const transactions=[new Transaction().add(initializeBuyback(program,payer,verifier.publicKey,mint)),new Transaction().add(create)];
for(let i=0;i<unique.length;i+=20)transactions.push(new Transaction().add(AddressLookupTableProgram.extendLookupTable({lookupTable:table,authority:payer,payer,addresses:unique.slice(i,i+20)})));
const latest=await connection.getLatestBlockhash();
const output=transactions.map((tx,i)=>{tx.feePayer=payer;tx.recentBlockhash=latest.blockhash;if(i===0)tx.partialSign(verifier);return {step:i+1,transaction:tx.serialize({requireAllSignatures:false}).toString('base64')};});
mkdirSync('outputs',{recursive:true});writeFileSync('outputs/buyback-setup.json',JSON.stringify({instaraMint:mint.toBase58(),buybackPolicy:buybackAddress(program).toBase58(),lookupTable:table.toBase58(),lastValidBlockHeight:latest.lastValidBlockHeight,transactions:output},null,2));
console.log('Prepared outputs/buyback-setup.json. Sign and submit the steps in order before expiry, wait for finalization, then set SOLANA_LOOKUP_TABLES. Nothing submitted.');
